# Generated by Django 5.2.3 on 2025-07-06 07:08

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for this bid', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount the seller is proposing', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('message', models.TextField(help_text="Seller's proposal or message to the buyer")),
                ('delivery_time', models.PositiveIntegerField(blank=True, help_text='Estimated delivery time in days', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this bid expires', null=True)),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether this bid has been accepted by the buyer')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this bid was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this bid was last modified')),
                ('created_by', models.ForeignKey(help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bids', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(help_text='The request this bid is for', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='user_requests.request')),
                ('seller', models.ForeignKey(help_text='User who submitted this bid', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amount', '-created_at'],
                'indexes': [models.Index(fields=['request', 'is_accepted', 'is_deleted'], name='bids_bid_request_3015de_idx'), models.Index(fields=['seller', 'is_accepted'], name='bids_bid_seller__dbd431_idx'), models.Index(fields=['created_at'], name='bids_bid_created_3cd9ec_idx'), models.Index(fields=['public_id'], name='bids_bid_public__46ad2f_idx'), models.Index(fields=['expires_at'], name='bids_bid_expires_f4d50c_idx')],
                'unique_together': {('request', 'seller')},
            },
        ),
    ]
